### ISSUE TITLE
Option to control DTD / external entity fetching during XML parsing

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#141]
I sure would be nice to be able to say "don't fetch external entities" so that parsing documents from websites that have references to random XHTML DTDs won't retrieve the DTD.  Of course, all bets are off as to whether that document will parse properly.

**Comment by ndw** [comment]
There's no easy way to do this. The ability to control that behavior is parser dependent. If you write your own subclass of the Xerces parser and set the appropriate features on that parser, and then tell Saxon to use that class for making parsers, you can do it.

See http://stackoverflow.com/questions/155101/make-documentbuilder-parse-ignore-dtd-references

And incidentally https://saxonica.plan.io/boards/3/topics/4746

Since neither Calabash nor Saxon can be sure what parser implementation is in use, it's difficult to imagine how this could be done more generally.

**Comment by alexmilowski** [comment]
Grumble.  An entity manager that returns empty strings would suffice.

**Comment by ndw** [comment]
I suppose that's a possibility.

**Comment by ndw** [comment]
Actually, I don't think that would work. Returning an empty string to the parser would probably do one of the following: read from STDIN, raise an error, default to reading the actual entity.
