### ISSUE TITLE
Configurable location of catalog.xml

### ISSUE THREAD

**Issue by josteinaj** [ndw/xmlcalabash1#212]
Would it be possible to configure additional entry names for the XML catalogs in the JARs? We keep them in our JARs as `META-INF/catalog.xml`.

https://github.com/ndw/xmlcalabash1/blob/693224b6e876a94507d9211e9ae664c611e43f52/src/main/java/com/xmlcalabash/core/XProcConfiguration.java#L219

**Comment by ndw** [comment]
Well...

I don't want to make it generally configurable because there's no point if half your jars have the catalog in one place and half have it in another. And having a configurable list of places to look seems...too complicated.

However, I think META-INF is maybe a reasonable place, so I'm happy to look there as well.

**Comment by josteinaj** [comment]
That would be great :)
