### ISSUE TITLE
Latest version? 1.1.21-97 or 1.1.21-98?

### ISSUE THREAD

**Issue by ilovezfs** [ndw/xmlcalabash1#276]
I cannot tell from https://github.com/ndw/xmlcalabash1/releases

Which should be in Homebrew?

**Comment by ndw** [comment]
Is there a formula that installs Saxon? The version of XML Calabash should match the version of Saxon. Otherwise, 98 is tracking the current release of Saxon. (To be subsumed by 99 eventually, of course.)

The problem is that the Saxon APIs change periodically so I have to ship slightly different versions of XML Calabash. Would that it were not so.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/saxon.rb

Looks like saxon formula needs to be upgraded too?

**Comment by ndw** [comment]
That looks ok. You could update it to 9.8.0.12, I guess. I should probably update XML Calabash to depend on that too. I'll do that in the next release.

**Comment by ilovezfs** [comment]
Voilà https://github.com/Homebrew/homebrew-core/pull/28566

**Comment by ilovezfs** [comment]
Thanks for the help @ndw
