### ISSUE TITLE
Performance very slow when resolving xincludes in certain circumstances, starting in 1.1.23

### ISSUE THREAD

**Issue by dwcramer** [ndw/xmlcalabash1#298]
An issue cropped up between 1.1.22 and 1.1.23, possibly introduced as a result of the fix for #273.
 In certain circumstances, resolving xincludes takes a very long time. I've posted an example doc at http://www.thingbag.net/slow_xinclude.zip

For this document, resolving xincludes takes much longer in 1.1.23 than 1.1.22:
* xmlcalabash 1.1.22: 20 seconds
* xmlcalabash 1.1.23: 83 minutes

There isn't a noticeable performance hit for most other documents, but when there is a large source file (e.g. 5.3M) with many (e.g. 170) tables and different tables are xincluded into the book in different places, the performance problem crops up.

```bash
dcramer@anatine ~/projects/slow_xinclude
$ cat xinclude.xpl
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" xmlns:c="http://www.w3.org/ns/xproc-step"
    version="1.0" name="main">
    <p:input port="source"/>
    <p:output port="result">
        <p:pipe port="result" step="xinclude"/>
    </p:output>
    <p:xinclude fixup-xml-base="true" name="xinclude"/>
</p:declare-step>

dcramer@anatine ~/projects/slow_xinclude
$ time java -jar ~/Downloads/xmlcalabash-1.1.23-97/xmlcalabash-1.1.23-97.jar -i slow_xinclude.xml -o out.xml xinclude.xpl

real	83m7.465s
user	80m23.892s
sys	0m51.265s

dcramer@anatine ~/projects/slow_xinclude
$ time java -jar ~/Downloads/xmlcalabash-1.1.22-98/xmlcalabash-1.1.22-98.jar -i slow_xinclude.xml -o out.xml xinclude.xpl

real	0m20.700s
user	0m28.958s
sys	0m1.881s
```

**Comment by ndw** [comment]
The problem here turns out to be the enormous document containing all those tables. The 1.2.3 implementation was laboriously walking over that whole document looking for `xi:include` elements, building a copy of the document as it went. I've added a quick check before doing that process to see if there are any `xi:include` elements. If not, we can just return the same document.

Unfortunately, that wasn't entirely sufficient to fix the problem. There's still an issue with copying the tables that are included. However, I discovered that the underlying `Reciever` API has an `append` method that performs better than my previous code.

Processing time is back down to tens of seconds, I believe. Let me know if you continue to have problems in the actual production environment.
