### ISSUE TITLE
On status of release 1.5.4-120

### ISSUE THREAD

**Issue by ZhongRuoyu** [ndw/xmlcalabash1#342]
Hi! [Homebrew](https://brew.sh/) maintainer here. While packaging XML Calabash 1.5.4-120 for Homebrew, we noticed that 1.5.4-110 is marked as the latest release instead. Perhaps strangely, the [releases page](https://github.com/ndw/xmlcalabash1/releases) on GitHub suggests that 1.5.4-120 was tagged *before* 1.5.4-110. May I confirm which of them is the latest version?

**Comment by ndw** [comment]
Hey! Let me start by saying thank you for packaging things up for Homebrew!

What's going on here is that XML Calabash 1.5.4 comes in three "flavors", one for Saxon 10.x, one for Saxon 11.x, and one for Saxon 12.x. That's what the -1x0 numbers mean at the end. (They'd make more sense if I'd had the foresight to name the 9.x versions 09x so that these could just be -1x, but nevermind.)

This is the first Saxon 12 release I've done, which is why I made sure that the 11 branch came out "after" it.

I recommend you package the 1.5.4-110 up (I'm guessing that 1.5.3-110 is what you did last time).

**Comment by ZhongRuoyu** [comment]
Thanks for your detailed clarification, @ndw! However, we *are* packaging [`saxon`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/saxon.rb) 12 (the current version is 12.1). Since `saxon` is the [dependency of `calabash`](https://github.com/Homebrew/homebrew-core/blob/31d05025d824f75dc5937a9a32af257e62225dc6/Formula/calabash.rb#L13), would it make more sense to use 1.5.4-120 then?

> I'm guessing that 1.5.3-110 is what you did last time

Yes, we have been packaging the -110 releases since 1.5.1-110: https://github.com/Homebrew/homebrew-core/commits/master/Formula/calabash.rb

**Comment by ndw** [comment]
Yes, if you're packaging Saxon 12, I think the`-120` flavor of XML Calabash makes sense.

**Comment by ZhongRuoyu** [comment]
Noted. Cheers!
