### ISSUE TITLE
Feature suggestion: step which prints its input to the console

### ISSUE THREAD

**Issue by j-maly** [ndw/xmlcalabash1#59]
I find cx:message step very useful for debugging XPath expressions. 
I would be glad for a similarly straightforward way to see the documents passed between the steps (especially the http requests and responses). So far, I am using p:store to save them to temporary files, but it is a bit cumbersome. So, consider adding a step 

cx:print-to-console

which behaves like p:identity, but also prints the documents from the input port to the console.

**Comment by argv-minus-one** [comment]
That's actually a standard feature of XProc: the [`<p:log>`](http://www.w3.org/TR/xproc/#p.log) element.

**Comment by j-maly** [comment]
Oh. 

And does Calabash support this step? It is not listed here http://xmlcalabash.com/docs/reference/ and when I try to use it, I get an error.

**Comment by argv-minus-one** [comment]
Yes, Calabash supports it. (It's not listed on the Calabash reference page because it's part of the standard.) But it's not a step; rather, you add it to another step, and it dumps documents sent to one of said step's output ports. For instance:

``` xml
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0">
    <p:load href="/usr/share/xml/schema/xml-core/catalog.xml">
        <p:log port="result"/>
    </p:load>

    <p:sink/>
</p:declare-step>
```

This loads `/usr/share/xml/schema/xml-core/catalog.xml` and does nothing with it, but the presence of `<p:log>` causes Calabash to dump its contents on the console, via `<p:load>`'s `result` port.

**Comment by ndw** [comment]
I think this one's already "fixed".
